### ISSUE TITLE
Plans for 1.21.2+ ArmorMaterial?

### ISSUE THREAD

**Issue by gniftygnome** [dhyces/trimmed#3]
I was going to switch to Trimmed for Cinderscapes in 1.21.2+, but then I discovered it isn't available.  So, as those of us who like pain will do, I tried to port it.  However, I quickly discovered they have yeeted the entire ArmorMaterial registry and materials are now just an anonymous collection of Item Settings...

Do you plan to move ahead with a 1.21.2+ version?  I guess the likely approach would be to create an ArmorMaterial registry in Trimmed, and fake up entries for the vanilla materials, then inject the material resource location and an accessor into ArmorItem ... or maybe inject it into ArmorMaterial and inject the entire ArmorMaterial into ArmorItem.

**Comment by dhyces** [comment]
I have started work on a 1.21.3 version (I will not be making a version for 1.21.2). Prior to ArmorMaterial registries, I had a different system for doing this. I imagine I will be reverting back to that for 1.21.3 and then adjust everything again for 1.21.4, due to the new item model system. I should hopefully have a version available by the end of the week

**Comment by gniftygnome** [comment]
Hmm, guess I'll make a separate Cinderscapes release for 1.21.2, then.

**Comment by dhyces** [comment]
Sorry, I just don't find it worth supporting 1.21.2 when 1.21.3 is just a hotfix for that version. Aside from that, 1.21.3 is now released https://modrinth.com/mod/trimmed/versions.
